name: Build

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    name: build-images
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template: [
          'default'
        ]
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/anyfiddle/runtime-images/${{ matrix.template }}
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          context: ./${{ matrix.template }}

